### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by pyToshka** [Hygieia/ExecDashboard#14] opened 2018-07-02 07:06 UTC
Hello, I tried to build execdashboard and have gotten a lot errors.
```
mvn install clean
[ERROR] npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/common@^2.2.3 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/core@^2.2.3 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of zone.js@^0.7.2 but none is installed. You must install peer dependencies yourself.
[ERROR] 
[INFO] up to date in 4.276s
[INFO] 
[INFO] --- maven-assembly-plugin:2.6:single (create-archive) @ exec-ui ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:HygieiaExec ............... SUCCESS [  0.716 s]
[INFO] com.capitalone.dashboard:exec-core ................. SUCCESS [  5.396 s]
[INFO] com.capitalone.dashboard:exec-analysis ............. SUCCESS [  3.777 s]
[INFO] com.capitalone.dashboard:exec-api .................. SUCCESS [  5.818 s]
[INFO] com.capitalone.dashboard:exec-ui ................... FAILURE [  5.539 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.720 s
[INFO] Finished at: 2018-07-02T10:59:30+04:00
[INFO] Final Memory: 102M/1083M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (create-archive) on project exec-ui: Error reading assemblies: Error locating assembly descriptor: assembly/bin.xml
[ERROR] 
[ERROR] [1] [INFO] Searching for file location: /Users/projects/tools/ExecDashboard/exec-ui/assembly/bin.xml
[ERROR] 
[ERROR] [2] [INFO] File: /Users/projects/tools/ExecDashboard/exec-ui/assembly/bin.xml does not exist.
[ERROR] 
[ERROR] [3] [INFO] File: /Users/projects/tools/ExecDashboard/assembly/bin.xml does not exist.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :exec-ui
```
Can you please help me?

**Comment by subodhbattina** [comment] 2018-07-02 15:04
@pyToshka : As a work around, you can build the exec-ui separately. 
Basically, cd into "exec-ui" folder, and then run "npm install", and let it complete: This will bring down all the dependencies.

In order to bring up the application:
1. Start your database
2. Start your API
3. And then go to exec-ui folder and run "npm run <environment>", where environment could be "local" or "prod".

We will look into exec-ui build failure and get back to you. Let us know if you have any other questions. Thanks

**Comment by pyToshka** [comment] 2018-07-12 03:47
Hi @subodhbattina 
I try to build exec-ui, but i got error
`
$ npm run local

> hygieia-executive@0.0.0 local /tmp/projects/tools/ExecDashboard/exec-ui
> ng serve --host=0.0.0.0 --port=4200 --proxy-config=proxy.config.json --env=local

As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/tmp/projects/tools/ExecDashboard/exec-ui/node_modules/angular-cli/tasks/serve.js:22:61)
    at /tmp/projects/tools/ExecDashboard/exec-ui/node_modules/angular-cli/commands/serve.run.js:22:22
    at process._tickCallback (internal/process/next_tick.js:109:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hygieia-executive@0.0.0 local: `ng serve --host=0.0.0.0 --port=4200 --proxy-config=proxy.config.json --env=local`
npm ERR! Exit status 1

`

**Comment by subodhbattina** [comment] 2018-07-24 15:04
@pyToshka : Sorry for the delay in responding, did you do a ```npm install``` first under "exec-ui", before running ```npm run local```?

**Comment by venkateshmadala** [comment] 2018-08-04 21:56
@subodhbattina : I am also facing same issue. I ran npm install in exec-ui then only I am trying build the project. But same issue I am facing.

**Comment by mmm13** [comment] 2018-08-14 22:04
@subodhbattina  :  Is there any update on the exec-ui build failure?  I'm experiencing the same issue ```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (create-archive) on project exec-ui: Error reading assemblies: Error locating assembly descriptor: assembly/bin.xml ```




I can run `npm run local` under exec-ui but I still need to be able to build the project.

**Comment by jigneshmehta1984** [comment] 2018-08-16 09:25
I'm facing similar issues while doing executive dashboard build. Please suggest if 
- Any quick workaround available for this.
I have tried
- Any permanent fix is about to be introduced?

I'm using Win 10 machine, with node v8.9.1 and npm v6.3.0.

Below are error details:

[INFO] Building com.capitalone.dashboard:exec-ui 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ exec-ui ---
[INFO]
[INFO] >>> maven-pmd-plugin:3.6:check (default) > :pmd @ exec-ui >>>
[INFO]
[INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ exec-ui ---
[INFO]
[INFO] <<< maven-pmd-plugin:3.6:check (default) < :pmd @ exec-ui <<<
[INFO]
[INFO] --- maven-pmd-plugin:3.6:check (default) @ exec-ui ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:prepare-agent (default) @ exec-ui ---
[INFO] argLine set to -javaagent:C:\\Users\\JMehta\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.6.201602180812\\org.jacoco.agent-0.7.6.201602180812-runtime.jar=destfile=C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\target\\jacoco.exec
[INFO]
[INFO] --- frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) @ exec-ui ---
[INFO] Found proxies: []
[INFO] Node v9.4.0 is already installed.
[INFO] NPM 5.6.0 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:0.0.29:npm (npm install) @ exec-ui ---
[INFO] Found proxies: []
[INFO] Running 'npm install' in C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui
[INFO]
[INFO] > node-sass@4.5.3 install C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\node-sass
[INFO] > node scripts/install.js
[INFO]
[INFO] Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
[ERROR] Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":
[ERROR]
[ERROR] HTTP error 404 Not Found
[ERROR]
[ERROR] Hint: If github.com is not accessible in your location
[ERROR]       try setting a proxy via HTTP_PROXY, e.g.
[ERROR]
[ERROR]       export HTTP_PROXY=http://example.com:1234
[ERROR]
[ERROR] or configure npm proxy via
[ERROR]
[ERROR]       npm config set proxy http://example.com:8080
[INFO]
[INFO] > node-sass@4.5.3 postinstall C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\node-sass
[INFO] > node scripts/build.js
[INFO]
[INFO] Building: C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node\node.exe C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[ERROR] gyp info it worked if it ends with ok
[ERROR] gyp verb cli [ 'C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\node\\node.exe',
[ERROR] gyp verb cli   'C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\node_modules\\node-gyp\\bin\\node-gyp.js',
[ERROR] gyp verb cli   'rebuild',
[ERROR] gyp verb cli   '--verbose',
[ERROR] gyp verb cli   '--libsass_ext=',
[ERROR] gyp verb cli   '--libsass_cflags=',
[ERROR] gyp verb cli   '--libsass_ldflags=',
[ERROR] gyp verb cli   '--libsass_library=' ]
[ERROR] gyp info using node-gyp@3.6.2
[ERROR] gyp info using node@9.4.0 | win32 | x64
[ERROR] gyp verb command rebuild []
[ERROR] gyp verb command clean []
[ERROR] gyp verb clean removing "build" directory
[ERROR] gyp verb command configure []
[ERROR] gyp verb check python checking for Python executable "python2" in the PATH
[ERROR] gyp verb `which` failed Error: not found: python2
[ERROR] gyp verb `which` failed     at getNotFoundError (C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\which\which.js:13:12)
[ERROR] gyp verb `which` failed     at F (C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\which\which.js:68:19)
[ERROR] gyp verb `which` failed     at E (C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\which\which.js:80:29)
[ERROR] gyp verb `which` failed     at C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\which\which.js:89:16
[ERROR] gyp verb `which` failed     at C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\isexe\index.js:42:5
[ERROR] gyp verb `which` failed     at C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\isexe\windows.js:36:5
[ERROR] gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
[ERROR] gyp verb `which` failed  python2 { Error: not found: python2
[ERROR] gyp verb `which` failed     at getNotFoundError (C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\which\which.js:13:12)
[ERROR] gyp verb `which` failed     at F (C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\which\which.js:68:19)
[ERROR] gyp verb `which` failed     at E (C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\which\which.js:80:29)
[ERROR] gyp verb `which` failed     at C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\which\which.js:89:16
[ERROR] gyp verb `which` failed     at C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\isexe\index.js:42:5
[ERROR] gyp verb `which` failed     at C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\isexe\windows.js:36:5
[ERROR] gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
[ERROR] gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\node_modules\\which\\which.js:80:29)\n    at C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\node_modules\\which\\which.js:89:16\n    at C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\node_modules\\isexe\\index.js:42:5\n    at C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
[ERROR] gyp verb `which` failed   code: 'ENOENT' }
[ERROR] gyp verb check python checking for Python executable "python" in the PATH
[ERROR] gyp verb `which` succeeded python C:\Python27\python.EXE
[ERROR] gyp verb check python version `C:\Python27\python.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.12\r\n"
[ERROR] gyp verb get node dir no --target version specified, falling back to host node version: 9.4.0
[ERROR] gyp verb command install [ '9.4.0' ]
[ERROR] gyp verb install input version string "9.4.0"
[INFO] up to date in 77.375s
[ERROR] gyp verb install installing version: 9.4.0
[ERROR] gyp verb install --ensure was passed, so won't reinstall if already installed
[ERROR] gyp verb install version not already installed, continuing with install 9.4.0
[ERROR] gyp verb ensuring nodedir is created C:\Users\JMehta\.node-gyp\9.4.0
[ERROR] gyp verb created nodedir C:\Users\JMehta\.node-gyp\9.4.0
[ERROR] gyp http GET https://nodejs.org/download/release/v9.4.0/node-v9.4.0-headers.tar.gz
[ERROR] gyp WARN install got an error, rolling back install
[ERROR] gyp verb command remove [ '9.4.0' ]
[ERROR] gyp verb remove using node-gyp dir: C:\Users\JMehta\.node-gyp
[ERROR] gyp verb remove removing target version: 9.4.0
[ERROR] gyp verb remove removing development files for version: 9.4.0
[ERROR] gyp ERR! configure error
[ERROR] gyp ERR! stack Error: self signed certificate in certificate chain
[ERROR] gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1041:34)
[ERROR] gyp ERR! stack     at TLSSocket.emit (events.js:160:13)
[ERROR] gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:638:8)
[ERROR] gyp ERR! System Windows_NT 10.0.15063
[ERROR] gyp ERR! command "C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\node\\node.exe" "C:\\Jignesh\\Git\\Hygieia_Exec_3_0\\exec-ui\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[ERROR] gyp ERR! cwd C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\node-sass
[ERROR] gyp ERR! node -v v9.4.0
[ERROR] gyp ERR! node-gyp -v v3.6.2
[ERROR] gyp ERR! not ok
[ERROR] Build failed with error code: 1
[ERROR] npm WARN rollback Rolling back readable-stream@2.2.9 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\node_modules\fsevents\node_modules'
[ERROR] npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/common@^2.2.3 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/core@^2.2.3 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of zone.js@^0.7.2 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
[ERROR] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[ERROR] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules\node-sass):
[ERROR] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 postinstall: `node scripts/build.js`
[ERROR] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
[ERROR]
[INFO]
[INFO] --- maven-assembly-plugin:2.6:single (create-archive) @ exec-ui ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:HygieiaExec ............... SUCCESS [ 10.909 s]
[INFO] com.capitalone.dashboard:exec-core ................. SUCCESS [01:05 min]
[INFO] com.capitalone.dashboard:exec-analysis ............. SUCCESS [ 51.425 s]
[INFO] com.capitalone.dashboard:exec-api .................. SUCCESS [ 29.625 s]
[INFO] com.capitalone.dashboard:exec-ui ................... FAILURE [01:39 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:20 min
[INFO] Finished at: 2018-08-16T11:30:19+05:30
[INFO] Final Memory: 99M/349M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (create-archive) on project exec-ui: Error reading assemblies: Error locating assembly descriptor: assembly/bin.xml
[ERROR]
[ERROR] [1] [INFO] Searching for file location: C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\assembly\bin.xml
[ERROR]
[ERROR] [2] [INFO] File: C:\Jignesh\Git\Hygieia_Exec_3_0\exec-ui\assembly\bin.xml does not exist.
[ERROR]
[ERROR] [3] [INFO] File: C:\Jignesh\Git\Hygieia_Exec_3_0\assembly\bin.xml does not exist.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :exec-ui

**Comment by xpdable** [comment] 2018-09-03 05:08
Same error even succeed 'npm install' in exec-ui.

> [INFO] --- maven-assembly-plugin:2.6:single (create-archive) @ exec-ui ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:HygieiaExec ............... SUCCESS [  2.303 s]
[INFO] com.capitalone.dashboard:exec-core ................. SUCCESS [ 14.544 s]
[INFO] com.capitalone.dashboard:exec-analysis ............. SUCCESS [ 10.996 s]
[INFO] com.capitalone.dashboard:exec-api .................. SUCCESS [ 14.144 s]
[INFO] com.capitalone.dashboard:exec-ui ................... FAILURE [ 12.379 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 55.343 s
[INFO] Finished at: 2018-09-03T05:06:30Z
[INFO] Final Memory: 103M/246M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (create-archive) on project exec-ui: Error reading assemblies: Error locating assembly descriptor: assembly/bin.xml
[ERROR]
[ERROR] [1] [INFO] Searching for file location: /opt/hygieia/ExecDashboard/exec-ui/assembly/bin.xml
[ERROR]
[ERROR] [2] [INFO] File: /opt/hygieia/ExecDashboard/exec-ui/assembly/bin.xml does not exist.
[ERROR]
[ERROR] [3] [INFO] File: /opt/hygieia/ExecDashboard/assembly/bin.xml does not exist.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :exec-ui

**Comment by xpdable** [comment] 2018-09-03 07:26
To who meets the error of @angular/flex-layout please read: https://github.com/angular/flex-layout/issues/344
Then you could modify the package.json to use 2.0.0-beta.8, and remove the package-lock.json once.
Rebuild exec-ui in maven, @angular/flex-layout will resolved.
However the exec-ui/assembly error is still there

**Comment by xpdable** [comment] 2018-09-03 07:45
@subodhbattina besides my above comments that is obviously we are lack of file/folder :  **assembly/bin.xml**

> <artifactId>maven-assembly-plugin</artifactId>
            <version>2.6</version>
            <configuration>
                <descriptor>assembly/bin.xml</descriptor>

Could you help to fix, thanks.
Have to go to developer guide to try to build in work around.

**Comment by jochenparm** [comment] 2019-02-13 10:55
I'm having this same issue.
It's quite disappointing that no one from Hygieia team is responding here anymore.
I mean, the build isn't working on the master branch, isn't that the minimal support they could supply...

**Comment by rvema** [comment] 2019-02-13 12:05
Did you try the suggestions mentioned above?

**Comment by jochenparm** [comment] 2019-02-13 12:18
I did. Plenty of other errors ensued.
The error seems quite straightforward initially: there's a missing file? Or is it missing since a step in the build chain failed?
I'm deploying the Hygieia toolchain on Kubernetes, so I want to get it up and running using the Docker images. As far as I understand, npm run local won't fix that.
If the problem is due to having the wrong build environment, maybe you guys could share a Dockerfile/image that has the necessary build dependencies? I've read all of the documentation multiple times, next step for me is learning how the build chain is composed so I can debug it but that seems like a large investment of my(/my employers) time.

**Comment by rvema** [comment] 2019-02-13 14:23
We are working on pushing the docker Iimages to dockerhub. We will update you as soon as they are published

**Comment by jochenparm** [comment] 2019-02-13 18:40
@rvema Thank you, that would be perfect!
If you're interested (and to show some gratitude), I could create a couple of pull-requests with Helm charts for various configurations of both the Hygieia product and exec dashboards and their collectors.
Maybe you already have these for internal use?
I'm not asking for a commitment here, but do you have an idea on when I could expect these images to appear on Dockerhub? I'm asking since I'm under a deadline and I'd need to know whether I need to continue trying to crack this myself or not, not trying to pressure you.

**Comment by jochenparm** [comment] 2019-02-19 10:26
@rvema Any update?

**Comment by Sbrenthughes** [comment] 2019-02-28 23:21
Pushing a fix for this issue. Once https://github.com/Hygieia/ExecDashboard/pull/45 is reviewed and merged this will be resolved.

**Closed** 2019-03-01 16:00 UTC

**Comment by Sbrenthughes** [comment] 2019-03-01 17:54
This build issue is resolved. Please pull the latest and try again. Docker enhancements will be coming later but not within the next few weeks, likely.
